version: '2'

services:
  app:
    build: .
    command: >
      gunicorn -b 0.0.0.0:$PORT
      --access-logfile -
      --reload
      "app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'